### ISSUE TITLE
Remove peerDependencies

### ISSUE THREAD

**Issue by Mister-Hope** [duereg/no-cliches#15]
Users DO NOT need to install those packages to use this package, so please remove 

https://github.com/duereg/no-cliches/blob/00fdcb82e3c2e93c362276938fadc713adb2e72a/package.json#L47-L52

**Comment by Mister-Hope** [comment]
Is this repo still under maintenance?

**Comment by Mister-Hope** [comment]
@duereg

**Comment by duereg** [comment]
fixed in latest patch
